### PR TITLE
fix: build @fedimint/utils before apps

### LINKED ISSUE #109: @fedimint/utils needs to be built before `dev`
```
ERROR in src/setup/FederationSetup.tsx:14:32
TS2307: Cannot find module '@fedimint/utils' or its corresponding type declarations.
    12 | import { VerifyGuardians } from '../components/VerifyGuardians';
    13 | import { SetupComplete } from '../components/SetupComplete';
  > 14 | import { useTranslation } from '@fedimint/utils';
       |                                ^^^^^^^^^^^^^^^^^
    15 |
    16 | const PROGRESS_ORDER: SetupProgress[] = [
    17 |   SetupProgress.Start,
```
This happens on a first time run because `@fedimint/utils` hasn't been built yet for the first time. We fixed this same issue with `@fedimint/ui`: https://github.com/fedimint/ui/blob/ad46faa3b7b513b0c8d457e6a2301a1b8bfc9422/turbo.json#L27-L35

### PR DESCRIPTION
**Pull request by okjodom**
build `@fedimint/utils` before apps and build apps in mprocs shells

fixes #109

### CODE REVIEW

**Comment by justinmoon** [comment]
On master, if I clone this repo fresh and run `yarn` and `yarn mprocs` I get a log of import errors related to `@fedimint/*` packages as described in #109. 

I checkout out this branch and did the same, but I still get these errors:

image

**Comment by justinmoon** [comment]
Also, I think you can drop [this commit](96918c0dd3ddfa00c537950b617f0ed4a710a1af)

**Comment by okjodom** [comment]
need to give this a bit more consideration

**Comment by okjodom** [comment]
> The mprocs thing should be a simple fix; right now they're directly running `yarn dev` in their own directory which circumvents the turbo dependency graph. They just need to use `dev:gateway-ui` and `dev:guardian-ui` from root, which will respect the dependency graph.

makes sense!

**Review by wbobeirne — APPROVED** [review]

**Comment by justinmoon** [comment]
This worked for me ✅

**Pull request merged**
