### PR TITLE
fix: center header

### PR DESCRIPTION
**Pull request by Kodylow**
Centers header on all screens to match figma, also looks better on both desktop and mobile for gateway and guardian

image
image

image

### CODE REVIEW

**Comment by wbobeirne** [comment]
> also looks better on both desktop

idk man looking a little topsy turvy to in some spots to me, I think we should limit what we're changing to be limited in scope to guardian ui mobile setup unless we figure out a way to make it good everywhere

CleanShot 2023-11-14 at 15 13 43@2x

CleanShot 2023-11-14 at 15 15 55@2x

**Comment by Kodylow** [comment]
@wbobeirne kk will limit centering to mobile and on the desktop setup flow

**Comment by okjodom** [comment]
we need to pull the design folks back in :p

**Comment by Kodylow** [comment]
I'm meeting with @skyler tomorrow we're going to fix all the figma stuff and put it in a single file for us to reference

**Review by wbobeirne — CHANGES_REQUESTED** [review]
Going with #298 centering on mobile only instead

**Pull request closed without merging**
